name: Deploy Semantic Weaver Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mermaid2 rdflib
      - name: Validate RDF files
        run: |
          python -c "
          from rdflib import Graph
          g = Graph()
          g.parse('docs/ontology.ttl', format='turtle')
          g.parse('docs/project.ttl', format='turtle')
          print('RDF files validated successfully')
          "
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site
      - name: Build and serve MkDocs
        run: mkdocs build